import { test, expect } from '@playwright/test';

async function login(page, account) {
  await page.goto('/login');
  await page.getByLabel('Email address').fill(account + '@rhu.test');
  await page.getByLabel('Password', { exact: true }).fill('Password!');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/dashboard/);
}
test('desktop sidebar, service modal, alerts and logout', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page, 'admin');
  await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).click();
  await expect(page.locator('body')).toHaveClass(/sidebar-collapsed/);
  await page.reload();
  await expect(page.locator('body')).toHaveClass(/sidebar-collapsed/);
  await page.locator('.sidebar-logo-toggle').click();
  await expect(page.locator('body')).not.toHaveClass(/sidebar-collapsed/);
  await page.getByRole('separator', { name: 'Resize sidebar' }).focus();
  await page.keyboard.press('End');
  await expect(page.getByRole('separator', { name: 'Resize sidebar' })).toHaveAttribute('aria-valuenow', '420');
  const handle = await page.getByRole('separator', { name: 'Resize sidebar' }).boundingBox();
  await page.mouse.move(handle.x + handle.width / 2, handle.y + 100);
  await page.mouse.down();
  await page.mouse.move(handle.x + handle.width / 2 - 120, handle.y + 100, { steps: 5 });
  await page.mouse.up();
  await expect(page.getByRole('separator', { name: 'Resize sidebar' })).toHaveAttribute('aria-valuenow', '300');
  await page.reload();
  await expect(page.getByRole('separator', { name: 'Resize sidebar' })).toHaveAttribute('aria-valuenow', '300');
  await page.goto('/services');
  const manageService = page.getByRole('button', { name: /^Manage service:/ }).first();
  await manageService.hover();
  await expect(manageService).toHaveCSS('cursor', 'pointer');
  await page.getByRole('button', { name: '+ Add service', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await dialog.getByLabel('Service name (required)').fill('Browser fictional service');
  await dialog.getByLabel('Code (required)').fill('BROWSER_TEST');
  await dialog.getByRole('button', { name: 'Add service', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Service');
  await page.getByRole('button', { name: 'Dismiss notification' }).click();
  await expect(page.getByRole('status')).toBeHidden();
  await page.getByRole('button', { name: 'Manage service: Browser fictional service', exact: true }).click();
  await dialog.getByLabel('Code (required)').fill('BROWSER_EDIT');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(page.locator('tbody')).toContainText('BROWSER_EDIT');
  await page.getByRole('button', { name: 'Manage service: Browser fictional service', exact: true }).click();
  await dialog.getByRole('button', { name: 'Delete service', exact: true }).click();
  await dialog.getByRole('button', { name: 'Delete service', exact: true }).click();
  await expect(page.locator('tbody')).not.toContainText('Browser fictional service');
  await page.locator('[x-ref="accountButton"]').click();
  await page.getByRole('button', { name: 'Log out', exact: true }).click();
  await expect(page).toHaveURL(/login/);
  expect(errors).toEqual([]);
});
test('mobile navigation and role dashboard fit viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await login(page, 'nurse');
  await expect(page.getByRole('navigation')).toBeHidden();
  await page.getByRole('button', { name: 'Menu', exact: true }).click();
  await expect(page.getByRole('navigation')).toBeVisible();
  await page.getByRole('navigation').getByRole('link', { name: 'Initial assessment' }).click();
  await expect(page.getByRole('heading', { name: 'Initial assessment', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'storage/framework/testing/mobile-assessment.png', fullPage: true });
});
test('doctor ITR and dynamic prescription rows', async ({ page }) => {
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await login(page, 'doctor');
  await page.goto('/consultations/2/visits/2/itr');
  await page.getByRole('button', { name: 'Edit notes', exact: true }).click();
  await page.getByLabel('Assessment', { exact: true }).fill('Fictional browser assessment');
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await page.getByLabel('Diagnoses for analytics (optional)', { exact: true }).fill('Fictional browser condition');
  await page.getByRole('button', { name: 'Save ITR', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('ITR saved');
  await expect(page.getByLabel('Diagnoses for analytics (optional)', { exact: true })).toHaveValue('Fictional browser condition');
  await page.goto('/prescriptions/2/visits/2');
  await page.getByLabel('Medicine name', { exact: true }).fill('Fictional browser medicine');
  await page.getByLabel('Dosage', { exact: true }).fill('Demonstration only');
  await page.getByLabel('Frequency', { exact: true }).fill('Demonstration only');
  await page.getByLabel('Quantity prescribed', { exact: true }).fill('2');
  await page.getByRole('button', { name: 'Add medicine', exact: true }).click();
  await expect(page.getByLabel('Medicine name', { exact: true })).toHaveCount(2);
  await page.getByRole('button', { name: 'Remove medicine', exact: true }).last().click();
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('draft saved');
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Issue saved prescription' }).click();
  await expect(page.getByRole('status')).toContainText('issued');
  expect(errors).toEqual([]);
});
test('pharmacist release and admin PDF download', async ({ page, browser }) => {
  await login(page, 'pharmacist');
  await page.goto('/pharmacy/1/visits/1');
  await page.getByLabel('Quantity released now', { exact: true }).fill('1');
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Record release', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('release recorded');
  await expect(page.getByRole('heading', { name: 'Release history' })).toBeVisible();
  const context = await browser.newContext();
  const admin=await context.newPage();
  await login(admin,'admin');
  await admin.goto('/reports');
  const downloadPromise=admin.waitForEvent('download');
  await admin.getByRole('link',{name:'Download report PDF'}).click();
  const download=await downloadPromise;
  expect(download.suggestedFilename()).toBe('rhu-service-report.pdf');
  expect(await download.failure()).toBeNull();
  await admin.screenshot({path:'storage/framework/testing/admin-report.png',fullPage:true});
  await context.close();
});


test('analytics chart filters and mobile department limits', async ({ page, browser }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page, 'admin');
  await page.getByRole('navigation').getByRole('link', { name: 'Analytics', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'RHU analytics', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'ITR screening responses' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Most recorded diagnoses' })).toBeVisible();
  const flip = page.getByRole('button', { name: 'Flip Patient trends card', exact: true });
  await flip.click();
  await expect(flip).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('group', { name: 'Patient trends chart', exact: true })).toHaveCount(0);
  await flip.press('Enter');
  await expect(flip).toHaveAttribute('aria-pressed', 'false');
  await expect(page.getByRole('group', { name: 'Patient trends chart', exact: true })).toBeVisible();
  await page.screenshot({ path: 'storage/framework/testing/admin-analytics.png', fullPage: true });
  await page.getByLabel('From date', { exact: true }).fill('2001-01-01');
  await page.getByLabel('To date', { exact: true }).fill('2001-01-03');
  await page.getByRole('button', { name: 'Update analytics' }).click();
  await expect(page.getByRole('button', { name: 'Flip Daily patient visits card', exact: true })).toHaveCount(0);
  const point = page.getByRole('button', { name: '2001-01-02: 0 visits', exact: true });
  await point.hover();
  await expect(page.getByRole('status')).toContainText('2001-01-02: 0 visits');
  await point.click();
  await page.getByRole('heading', { name: 'Daily patient visits', exact: true }).hover();
  await expect(page.getByRole('status')).toContainText('2001-01-02: 0 visits');
  await point.focus();
  await point.press('Escape');
  await expect(page.getByRole('status')).toContainText('Hover or select');
  await point.press('Enter');
  await expect(point).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('link', { name: 'Go to this data', exact: true }).click();
  await expect(page).toHaveURL(/\/visits\?/);
  await expect(page.getByRole('heading', { name: 'Patient visits', exact: true })).toBeVisible();
  await expect(page.getByLabel('From date', { exact: true })).toHaveValue('2001-01-02');
  await expect(page.getByLabel('To date', { exact: true })).toHaveValue('2001-01-02');
  await page.goto('/analytics?from=2001-01-02&to=2001-01-02');
  await page.getByRole('navigation', { name: 'Chart interval' }).getByRole('link', { name: 'Monthly', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Monthly patient visits', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '2001-01-02: 0 visits', exact: true })).toBeVisible();

  expect(errors).toEqual([]);
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const nurse = await context.newPage();
  await login(nurse, 'nurse');
  await nurse.goto('/analytics?overview=1');
  await expect(nurse.getByRole('heading', { name: 'Initial assessment', exact: true })).toBeVisible();
  await expect(nurse.getByRole('heading', { name: 'ITR screening responses' })).toHaveCount(0);
  await expect(nurse.getByRole('heading', { name: 'Patient trends', exact: true })).toHaveCount(0);
  expect(await nurse.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await nurse.screenshot({ path: 'storage/framework/testing/nurse-analytics.png', fullPage: true });
  await context.close();
});


test('admin opens read-only patient visit details', async ({ page }) => {
  await login(page, 'admin');
  await page.goto('/visits');
  await page.getByRole('link', { name: 'View details', exact: true }).first().click();
  await expect(page.getByRole('heading', { name: 'Visit details', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Completion details' })).toBeVisible();
  await expect(page.getByText('Read-only administrative visit record.')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Complete visit', exact: true })).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('heading', { name: 'Completion details' })).toBeVisible();
  await page.getByRole('link', { name: 'Back to patient visits' }).click();
  await expect(page.getByRole('heading', { name: 'Patient visits', exact: true })).toBeVisible();
});
