<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans,sans-serif;font-size:9px;color:#172c25}h1{font-size:19px}h2{font-size:12px;border-bottom:1px solid #bbb;padding-bottom:3px;margin-top:10px;margin-bottom:5px;page-break-after:avoid}p{orphans:3;widows:3;white-space:pre-wrap;overflow-wrap:break-word}table{width:100%;border-collapse:collapse}td{padding:3px;border-bottom:1px solid #eee}thead{display:table-header-group}</style></head><body>
<h1>RHU Calasiao - Internal visit summary</h1><p>{{ $patient->full_name }} | {{ $patient->patient_number }}<br>{{ $visit->visit_number }} | {{ $visit->visit_date->format('Y-m-d') }} | {{ $visit->service->name }}</p>
<p>Confidential clinical record. This is not a signed medical certificate, referral or prescription.</p>
<h2>Current vital signs</h2><table>@foreach(['temperature'=>'Temperature (Celsius)','pulse_rate'=>'Pulse (bpm)','respiratory_rate'=>'Respiratory rate (cpm)','systolic_bp'=>'Systolic BP (mmHg)','diastolic_bp'=>'Diastolic BP (mmHg)','oxygen_saturation'=>'O2 saturation (%)','height_cm'=>'Height (cm)','weight_kg'=>'Weight (kg)'] as $field=>$label)<tr><td>{{ $label }}</td><td>{{ $visit->vitalSign?->$field ?? 'Not recorded' }}</td></tr>@endforeach</table>
<h2>ITR</h2>@if($visit->treatmentRecord)
<table>@foreach(App\Models\TreatmentRecord::QUESTIONS as $field=>$label)<tr><td>{{ $label }}</td><td>{{ $visit->treatmentRecord->$field === null ? 'Not recorded' : ($visit->treatmentRecord->$field ? 'Yes' : 'No') }}</td></tr>@endforeach</table>
@foreach(['medicine_details'=>'Current medicine details','lmp'=>'LMP','assessment'=>'Assessment','planning'=>'Planning','remarks'=>'Remarks'] as $field=>$label)<h2>{{ $label }}</h2><p>{{ $field === 'lmp' ? ($visit->treatmentRecord->lmp?->format('Y-m-d') ?? 'Not recorded') : ($visit->treatmentRecord->$field ?? 'Not recorded') }}</p>@endforeach
<h2>Doctor-entered diagnoses</h2><p>{{ implode("; ", $visit->treatmentRecord->diagnoses ?? []) ?: "Not recorded" }}</p>
@else<p>No ITR recorded.</p>@endif
<p>Generated {{ now('Asia/Manila')->format('Y-m-d H:i') }} (Asia/Manila). Current profile and measurements are shown; ITR objective snapshots remain in the application.</p></body></html>
