<p><strong>Visit dates:</strong> {{ $from }} to {{ $to }} (inclusive, Asia/Manila)</p>
<p><strong>Services:</strong> {{ $serviceLabel }}</p>
<p><strong>Status:</strong> {{ $status === 'all' ? 'All statuses' : $status }} | <strong>Contents:</strong> {{ $formatLabel }}</p>
<p><strong>Generated:</strong> {{ $generatedAt }} (Asia/Manila) | <strong>Generated by:</strong> {{ $generatedBy }}</p>
<p class="metrics"><strong>{{ $total }} visits</strong> | {{ $patients }} distinct patients @if($status !== 'COMPLETED') | {{ $open }} open @endif @if($status !== 'OPEN') | {{ $completed }} completed @endif</p>
<p class="muted">Counts describe visits by requested service, not procedures performed. Distinct patients are counted once across the selected visits. Percentages use the filtered visit total; rounding may affect the sum. Empty periods are omitted.</p>
@if($format !== 'register')
    <h2>Summary by {{ strtolower($groupLabel) }}</h2>
    <table><thead><tr><th>{{ $groupLabel }}</th><th>Visits</th>@if($status !== 'COMPLETED')<th>Open</th>@endif @if($status !== 'OPEN')<th>Completed</th>@endif<th>Share (%)</th></tr></thead><tbody>
    @forelse($rows as $row)<tr><td>{{ $row['service'] }}</td><td>{{ $row['total'] }}</td>@if($status !== 'COMPLETED')<td>{{ $row['open'] }}</td>@endif @if($status !== 'OPEN')<td>{{ $row['completed'] }}</td>@endif<td>{{ number_format($row['percentage'],1) }}%</td></tr>@empty<tr><td colspan="{{ $status === 'all' ? 5 : 4 }}">No visits match the selected filters.</td></tr>@endforelse
    </tbody></table>
@endif
@if($format !== 'summary')
    <h2>Administrative visit register</h2>
    @unless($export)<p class="muted">Preview shows 25 visits per page. The PDF includes all matching visits, up to the 2,000-visit limit.</p>@endunless
    <table><thead><tr><th>Visit date</th><th>Visit number</th><th>Requested service</th><th>Status</th>@foreach($columnLabels as $key=>$label)@if(in_array($key,$columns))<th>{{ $label }}</th>@endif@endforeach</tr></thead><tbody>
    @forelse($register as $visit)<tr>
        <td>{{ $visit->visit_date->format('Y-m-d') }}</td><td>{{ $visit->visit_number }}</td><td>{{ $names[$visit->service_id] ?? 'Former service' }}</td><td>{{ $visit->status }}</td>
        @foreach($columnLabels as $key=>$label)@if(in_array($key,$columns))<td>@if($key === 'queue_reference'){{ $visit->queue_reference ?? 'Not recorded' }}@elseif($key === 'completed_at'){{ $visit->completed_at?->timezone('Asia/Manila')->format('Y-m-d H:i:s') ?? 'Not recorded' }}@else{{ $visit->completedBy?->name ?? 'Not recorded' }}@endif</td>@endif@endforeach
    </tr>@empty<tr><td colspan="{{ 4 + count($columns) }}">No visits match the selected filters.</td></tr>@endforelse
    </tbody></table>
@endif
<p class="muted">Internal administrative report. Archived patients excluded. Not an official DOH submission. Patient identities, completion remarks and clinical text are excluded. Visit and queue references may still be linkable to records; share only with authorized recipients.</p>
